# Generated by Django 4.2.5 on 2023-10-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_head0',
            field=models.CharField(default=' ', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_head1',
            field=models.CharField(default=' ', max_length=5000),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content_head2',
            field=models.CharField(default=' ', max_length=5000),
        ),
    ]
