# Generated by Django 4.2.5 on 2023-09-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_orders_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
