# Generated by Django 4.2.5 on 2023-09-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_decs', models.CharField(max_length=5000)),
                ('timetamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
